apiVersion: v2
name: streamlink-chart
description: A Helm chart for Kubernetes to run streamlink jobs for different streamers
type: application
version: 4.0.23
appVersion: 4.0.23
home: https://github.com/liofal/streamlink
sources:
  - https://github.com/liofal/streamlink
maintainers:
  - name: liofal
    email: lfa@gmx.com
    url: https://github.com/liofal
